blog/urls.py
from django.urls import path, include
from blog.apps import BlogConfig
from blog.views import (
    BlogCreateView,
    BlogListView,
    BlogDetailView,
    BlogUpdateView,
    BlogDeleteView,
)
from django.views.decorators.cache import never_cache

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogListView.as_view(), name="list"),
    path("view/<int:pk>", BlogDetailView.as_view(), name="view"),
    path("create/", never_cache(BlogCreateView.as_view()), name="create"),
    path("edit/<int:pk>", never_cache(BlogUpdateView.as_view()), name="update"),
    path("delete/<int:pk>", BlogDeleteView.as_view(), name="delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from datetime import datetime

from django.db import models

NULLABLE = {"blank": True, "null": True}


class Blog(models.Model):
    """
    Модель сообщения блога
    """

    title = models.CharField(max_length=150, verbose_name="Заголовок")
    slug = models.CharField(max_length=150, verbose_name="slug", **NULLABLE)
    body = models.TextField(verbose_name="Содержимое")
    preview = models.ImageField(
        upload_to="blog/photo",
        verbose_name="Изображение",
        **NULLABLE,
    )
    created_at = models.DateField(
        auto_now_add=True,
        verbose_name="Дата создания",
    )
    is_published = models.BooleanField(default=True, verbose_name="Опубликовано")
    views_count = models.PositiveIntegerField(
        default=0, editable=False, verbose_name="Просмотры"
    )

    def __str__(self):
        return f"{self.title} {self.created_at}"

    class Meta:
        verbose_name = "блог"
        verbose_name_plural = "блог"

blog/views.py
from django.shortcuts import render
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
)
from django.urls import reverse_lazy, reverse

from blog.models import Blog

from pytils.translit import slugify
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin


class BlogCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """
    Контроллер создания сообщения
    """

    model = Blog
    fields = (
        "title",
        "body",
        "preview",
    )
    permission_required = "blog.add_blog"
    success_url = reverse_lazy("blog:list")

    def form_valid(self, form):
        """
        Формирования slug для названия сообщения
        """
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    """
    Контроллер редактирования сообщения
    """

    model = Blog
    fields = (
        "title",
        "body",
        "preview",
    )
    permission_required = "blog.change_blog"

    def form_valid(self, form):
        """
        Формирования slug для названия сообщения
        """
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        """
        Перенаправление на нужное сообщение после редактирования
        """
        return reverse("blog:view", args=[self.kwargs.get("pk")])


class BlogListView(ListView):
    """
    Контроллер страницы просмотра сообщений блога
    """

    model = Blog

    def get_queryset(self, *args, **kwargs):
        """
        Отображение тоалько опубликованных сообщений
        """
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    """
    Контроллер детального просмотра сообщений
    """

    model = Blog
    permission_required = "blog.view_blog"

    def get_object(self, queryset=None):
        """
        Счетчик просмотров
        """
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save(update_fields=["views_count"])
        return self.object


class BlogDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    """
    Контроллер удаления сообщения
    """

    model = Blog
    permission_required = "blog.delete_blog"
    success_url = reverse_lazy("blog:list")

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/home.html' %}

{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить запись "{{ object.title }}?"</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'blog:list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}

<div class="row text-center">

    <div class="col-6">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <img class='card-img-top' src="{{ object.preview | media_filter }}">
                <h4 class="my-0 font-weight-normal">{{ object.title }} ({{ object.slug }})</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">

                    <p>{{ object.body}}</p>

                    <dl> Дата создания: {{ object.created_at }}</dl>
                    <dl> Количество просмотров: {{ object.views_count }}</dl>


                </ul>
                <div class="btn-group">

                    <a class="btn btn-lg btn-block btn-outline-primary"
                       href="{% url 'blog:list' %}" role="button">Назад</a>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}

                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}

<div class="row text-center">
    <div class="col-12 mb-5">

        {% if perms.blog.add_blog %}
            <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить запись в блог</a>
        {% endif %}

    </div>

    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">

            <div class="card-body">
                <div class="card-header">
                    <img class='card-img-top' src="{{ object.preview|media_filter}}">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <p class="card-text">

                    {{ object.body }}

                </p>
                <div class="card-footer">
                    <dl> Дата создания: {{ object.created_at }}</dl>
                    <dl> Количество просмотров: {{ object.views_count }}</dl>
                </div>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        {% if perms.blog.view_blog %}
                        <a href="{% url 'blog:view' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">View</a>
                        {% endif %}
                        {% if perms.blog.change_blog %}
                        <a href="{% url 'blog:update' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Edit</a>
                        {% endif %}
                        {% if perms.blog.delete_blog %}
                        <a href="{% url 'blog:delete' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-danger">Delete</a>
                        {% endif %}

                    </div>
                </div>

            </div>
        </div>
    </div>


    {% endfor %}
</div>

{% endblock %}