blog/urls.py
from django.urls import path, include
from blog.apps import BlogConfig
from blog.views import (
    BlogCreateView,
    BlogListView,
    BlogDetailView,
    BlogUpdateView,
    BlogDeleteView,
)
from django.views.decorators.cache import never_cache

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogListView.as_view(), name="list"),
    path("view/<int:pk>", BlogDetailView.as_view(), name="view"),
    path("create/", never_cache(BlogCreateView.as_view()), name="create"),
    path("edit/<int:pk>", never_cache(BlogUpdateView.as_view()), name="update"),
    path("delete/<int:pk>", BlogDeleteView.as_view(), name="delete"),
]

catalog/urls.py
from django.urls import path, include
from catalog.apps import CatalogConfig
from catalog.views import (
    contact,
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    CategoryListView,
)
from django.views.decorators.cache import cache_page, never_cache


app_name = CatalogConfig.name

urlpatterns = [
    path("", ProductListView.as_view(), name="home"),
    path("contacts/", contact, name="contact"),
    path(
        "product/<int:pk>/",
        cache_page(60)(ProductDetailView.as_view()),
        name="product_about",
    ),
    path("create/", never_cache(ProductCreateView.as_view()), name="create_product"),
    path(
        "edit/<int:pk>/",
        never_cache(ProductUpdateView.as_view()),
        name="update_product",
    ),
    path("delete/<int:pk>/", ProductDeleteView.as_view(), name="delete_product"),
    path('category', CategoryListView.as_view(), name='category_list')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {"blank": True, "null": True}


class Category(models.Model):
    """
    Модель описывает категории товаров
    """

    name = models.CharField(
        max_length=100,
        verbose_name="Название категории",
        help_text="Введите название категории товара",
    )
    description = models.TextField(
        verbose_name="Описание категории",
        help_text="Введите описание категории товара",
        **NULLABLE,
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class Product(models.Model):
    """
    Модель описывает товар
    """

    name = models.CharField(
        max_length=100,
        verbose_name="Наименование",
        help_text="Введите наименование товара",
    )
    description = models.CharField(
        max_length=100, verbose_name="Описание", help_text="Введите описание товара"
    )
    photo = models.ImageField(
        upload_to="product/photo",
        verbose_name="Изображение",
        help_text="Загрузите фото товара",
        **NULLABLE,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        verbose_name="Категория",
        help_text="Введите категорию товара",
        related_name="products",
        **NULLABLE,
    )
    price = models.FloatField(
        verbose_name="Цена за покупку", help_text="Введите стоимость товара"
    )
    created_at = models.DateField(
        auto_now_add=True,
        verbose_name="Дата создания",
        help_text="Укажите дату записи в БД",
    )
    updated_at = models.DateField(
        auto_now=True,
        verbose_name="Дата последнего изменения",
        help_text="Укажите дату последнего изменения",
    )

    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        verbose_name="Владелец",
        help_text="Введите владельца товара",
        related_name="products",
        blank=True,
        null=True,
    )
    is_published = models.BooleanField(default=False, verbose_name="Опубликовано")

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        ordering = ["name", "category", "created_at", "updated_at"]
        permissions = [
            ("set_published_status", "can change status is_published"),
            ("can_edit_description", "can edit description"),
            ("can_edit_category", "can edit category"),
        ]

    def __str__(self):
        return f"{self.name} {self.category}"


class Version(models.Model):
    """
    Модель описывает версию товара
    """

    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="товар")
    number_of_version = models.FloatField(verbose_name="номер версии")
    title = models.CharField(max_length=150, verbose_name="название версии")
    is_actual = models.BooleanField(
        default=False, verbose_name="признак текущей версии"
    )

    def __str__(self):
        return f"{self.title}.версия {self.number_of_version}"

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"
        ordering = (
            "product",
            "is_actual",
        )

catalog/forms.py
from django import forms

from catalog.models import Product, Version
from config.settings import UNVALID_WORDS


class StyleFormMixin:
    """
    Стилизация формы
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


def string_to_words(my_str: str) -> list:
    """
    Функция преобразует строку в список слов, используется для валидации - поиске запрещенных слов
    В список включаются слова длиннее одной буквы с переводом в нижний регистр, без знаков препинания
    """
    output: list = my_str.split()
    output_list: list = []

    for item in output:
        word: str = ""

        for char in item:
            if char.isalpha():
                word += char
        if len(word) > 1:
            output_list.append(word.lower())
    return output_list


class ProductForm(StyleFormMixin, forms.ModelForm):
    """
    Форма для товара
    """

    class Meta:
        model = Product
        exclude = ("owner",)

    def clean_name(self):
        """
        Валидация названия товара
        """
        cleaned_data = self.cleaned_data["name"]
        cleaned_data_list = string_to_words(cleaned_data)
        for word in cleaned_data_list:
            if word in UNVALID_WORDS:
                raise forms.ValidationError("Текст содержит недопустимые слова")
        return cleaned_data

    def clean_description(self):
        """
        Валидация описания товара
        """
        cleaned_data = self.cleaned_data["description"]
        cleaned_data_list = string_to_words(cleaned_data)
        for word in cleaned_data_list:
            if word in UNVALID_WORDS:
                raise forms.ValidationError("Текст содержит недопустимые слова")
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    """
    Форма для версии товара
    """

    class Meta:
        model = Version
        fields = "__all__"


class ProductModeratorForm(StyleFormMixin, forms.ModelForm):
    """
    Форма товара для модератора
    """

    class Meta:
        model = Product
        fields = (
            "description",
            "category",
            "is_published",
        )

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Version, Category
from django.urls import reverse_lazy
from django.forms import inlineformset_factory
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied

from catalog.services import get_objects_from_cache


class ProductListView(ListView):
    """
    Контроллер перечня товаров
    """

    model = Product

    def get_context_data(self, **kwargs):
        """
        Расширяем данные информацией по актуальной версии товара
        """
        context_data = super().get_context_data(**kwargs)
        for product in context_data["object_list"]:
            actual_version = Version.objects.filter(
                product=product, is_actual=True
            ).first()
            product.actual_version = actual_version

        return context_data

    def get_queryset(self):
        """
        Вызов сервисной функции, для кэширования
        """
        return get_objects_from_cache(Product)


def contact(request):
    """
    Контроллер страницы с контактами
    """
    if request.method == "POST":
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        message = request.POST.get("message")
        print(f"You have new message from {name}({phone}): {message}")
    return render(request, "catalog/contact.html")


class ProductDetailView(LoginRequiredMixin, DetailView):
    """
    Контроллер детального отображения товара
    """

    model = Product

    def get_object(self, queryset=None):
        """
        Только владелец может просматривать карточук товара
        """
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            return self.object
        raise PermissionDenied


class ProductCreateView(LoginRequiredMixin, CreateView):
    """
    Контроллер создания товара
    """

    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:home")

    def form_valid(self, form):
        """
        Автоматическая привязка пользователя к продукту
        """
        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    """
    Контроллер обновления товара
    """

    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:home")

    def get_context_data(self, **kwargs):
        """
        Добавляем формсет для ввода версии продукта
        """
        context_data = super().get_context_data(**kwargs)
        SubjectFormset = inlineformset_factory(
            Product, Version, form=VersionForm, extra=1
        )
        if self.request.method == "POST":
            context_data["formset"] = SubjectFormset(
                self.request.POST, instance=self.object
            )
        else:
            context_data["formset"] = SubjectFormset(instance=self.object)

        return context_data

    def form_valid(self, form):
        """
        Обработка сохранения формсетов
        """
        formset = self.get_context_data()["formset"]
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def get_form_class(self):
        """
        Проверка, что пользователь владелец товара,
        Проверка прав модератора на редактирование товара
        """
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if (
                user.has_perm("catalog.set_published_status")
                and user.has_perm("catalog.can_edit_description")
                and user.has_perm("catalog.can_edit_category")
        ):
            return ProductModeratorForm
        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """
    Контроллер удаления товара
    """

    model = Product
    success_url = reverse_lazy("catalog:home")

    def test_func(self):
        """
        проверка на суперюзера
        """
        return self.request.user.is_superuser


class CategoryListView(ListView):
    """
    Контроллер для списка категорий
    """
    model = Category

    def get_queryset(self):
        """
        Вызов сервисной функции, для кэширования
        """
        return get_objects_from_cache(Category)

catalog/templates/catalog/category_list.html
{% extends 'catalog/home.html' %}
{% block content %}

<div class="row text-center">

    {% for object in object_list %}
    <div class="col-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <l1>Описание:</l1>
                    <li>{{ object.description | truncatechars:100 }}</li>
                </ul>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

catalog/templates/catalog/contact.html
<!doctype html>
<html lang="en">
<head>
    {% include 'catalog/includes/inc_menu.html' %}
</head>
<body>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        {% include 'catalog/includes/inc_footer.html' %}
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/home.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

    {% include 'catalog/includes/inc_menu.html' %}

</head>
<body>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный магазин</p>
</div>

<div class="container">

    {% block content %}
    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">

        {% include 'catalog/includes/inc_footer.html' %}

    </footer>

</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">

        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Удалить товар
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    <p>Хотите удалить товар "{{ object.name }} {{ object.description }}"</p>
                    <button type="submit" class="btn btn-primary">Подтвердить</button>
                    <a href="{% url 'catalog:home' %}" class="btn btn-warning">Отмена</a>
                </div>
            </div>
        </div>

    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}

<div class="row text-center">

    <div class="col-6">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <img class='card-img-top' src="{{ object.photo | media_filter }}">
                <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
            </div>
            <div class="card-body">
                <h2 class="card-title pricing-card-title">{{ object.price }} руб.</h2>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <p>Категория:</p>
                    <p>{{ object.category | title}}</p>
                    <p>Описание:</p>
                    <p>{{ object.description | truncatechars:100 }}</p>
                    <p>Дата создания объявления: {{ object.created_at }}</p>
                    <p>Дата изменения объявления: {{ object.updated_at }}</p>
                </ul>
                <div class="btn-group">
                    {% if perms.catalog.set_published_status and perms.catalog.can_edit_description and perms.catalog.can_edit_category or user == object.owner %}
                        <a class="btn btn-outline-primary" href="{% url 'catalog:update_product' object.pk %}" role="button">Редактировать</a>
                    {% endif %}
                    <a class="btn btn-outline-primary" href="{% url 'catalog:home' %}" role="button">Назад</a>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">

        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        {% if object %}
                        Редактировать товар
                        {% else %}
                        Добавить товар
                        {% endif %}
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>

        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Версии продукта
                    </h3>
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                        {% if not forloop.last %}
                            <hr>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>

    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}

<div class="row text-center">
    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'catalog:create_product' %}">Добавить товар</a>
    </div>

    {% for object in object_list %}
    {% if object.is_published %}
    <div class="col-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <img class='card-img-top' src="{{ object.photo | media_filter}}">
                <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
            </div>
            <div class="card-body">
                <h2 class="card-title pricing-card-title">{{ object.price }} руб.</h2>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <l1>Описание:</l1>
                    <li>{{ object.description | truncatechars:100 }}</li>
                    <li>
                        {% if object.actual_version%}
                        Актуальная версия: {{object.actual_version}}

                        {% endif %}
                    </li>
                </ul>
                <div class="btn-group">
                    {% if user == object.owner %}
                        <a class="btn btn-outline-primary" href="{% url 'catalog:product_about' object.pk %}" role="button">О товаре</a>
                    {% endif %}
                    {% if perms.catalog.set_published_status and perms.catalog.can_edit_description and perms.catalog.can_edit_category or user == object.owner %}
                        <a class="btn btn-outline-primary" href="{% url 'catalog:update_product' object.pk %}" role="button">Редактировать</a>
                    {% endif %}

                    {% if user.is_superuser %}
                    <a class="btn btn-outline-danger" href="{% url 'catalog:delete_product' object.pk %}" role="button">Удалить</a>
                    {% endif %}
                    <a class="btn btn-outline-primary" href="#" role="button">Купить</a>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>

{% endblock %}